#!/usr/bin/zsh

REPO_NAME=$1
curl \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token $GIT_TOKEN" \
  https://api.github.com/user/repos \
  -d "{\"name\":\"$REPO_NAME\", \"private\":true, \"auto_init\":true}" 

git clone git@github.com:$GIT_USER/$REPO_NAME
cd $REPO_NAME
sleep 1
echo "\nrepo creation by create_remote_repo" >> ./README.md
git add .
git commit -m "Initial Commit, automated"
git push 