#!/usr/bin/zsh

REPO_NAME=$1
curl \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token $GIT_TOKEN" \
  https://api.github.com/user/repos \
  -d '{"private":"true"}' \
  -d "{\"name\":\"$REPO_NAME\"}" \

git init
git remote add origin master
echo "repo creation by create_remote_repo" >> ./README.MD
git add README.MD
git commit "Initial Commit. Automated"
git push --set-upstream origin master