#!/usr/bin/zsh

REPO_NAME=$1
curl \
  -X DELETE \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token $GIT_TOKEN" \
  https://api.github.com/repos/$GIT_USER/$REPO_NAME 
echo 
if [ $? -eq 0 ] 
then
  echo "Repo $REPO_NAME deleted!"
fi